### ISSUE TITLE
Incorrect Arrow Physics.

### ISSUE THREAD

**Issue by AstoriaFloyd** [SmushyTaco/Legacy-Bows#1]
This is less of a bug with the mod, and more of an innaccuracy.
Inaccuracy of bows to be specific.
Some point after the combat update, I believe around 1.13, they changed arrows to inheret your velocity, adding it to the arrow, thus making it so that if you shoot while moving, it will drift in that direction.
I absolutely despise this, as it makes aiming while moving near impossible.
Could you remove arrows inheriting your momentum, to make them act like they did back in pre-1.9?

**Comment by SmushyTaco** [comment]
No
