### ISSUE TITLE
Sorry, cant find where I can talk with u!  

### ISSUE THREAD

**Issue by brayanluc** [SmushyTaco/Legacy-Bows#3]
I'm sorry, this is not a problem to the mod, I just cant find a way to talk with u (maybe i'm too dumd sorry) 
U have a plan to make the Extended Bows mod? Because I have the 3 Extended mod series and the bow actually do not have this feature, and that's sad! 
If u call me on discord we can chat about this, I can give u feedbacks of your mods and etc. 𝓜𝖚𝖓𝖎𝖓#4815

**Comment by SmushyTaco** [comment]
Probably won't be making an bow iterations of the enchant mods
